CREATE TABLE refresh_token
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token   VARCHAR(255),
    user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id)
);